# Site settings
title: 
email: mail@serdiuk.ch
author: Dmitry Serdiuk
description: "My Blog"
baseurl: ""
url: "http://serdiuk.ch"

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3

#highlighter: rouge